name: skycraft
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 4.0.2+0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  # firebase_messaging: ^14.9.1
  google_maps_flutter: ^2.6.1
  get: ^4.6.6
  firebase_storage: ^11.7.4

  flutter_advanced_avatar: ^1.5.0
  random_avatar: ^0.0.8
  super_cupertino_navigation_bar: ^2.1.2
  location: ^6.0.1
  flutter_rating_bar: ^4.0.1
  calendar_date_picker2: ^1.0.2
  geocoder2: ^1.4.0
  pinput: ^4.0.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.2
  video_player: ^2.8.7
  fluttertagger: ^2.0.0
  flutter_reaction_button: ^3.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#ffffff"
  image: "assets/Splash-light.png"

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/fonts/
  - assets/icons/

  # example:
  fonts:
  - family: Circular Std
    fonts:
    - asset: assets/fonts/circular-std-medium-500.ttf
