// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0xF39u8Tj7IbGd84qJUwVGXCC50IeQuo',
    appId: '1:167742209744:web:f5f18e0f73826c4a69e8d5',
    messagingSenderId: '167742209744',
    projectId: 'skykraft-e7fb7',
    authDomain: 'skykraft-e7fb7.firebaseapp.com',
    storageBucket: 'skykraft-e7fb7.appspot.com',
    measurementId: 'G-M24ZE1PQZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBeLu2kXtPEhZ5Nv9XbhQtXbdIGUv4IyM',
    appId: '1:167742209744:android:665290e37235d84e69e8d5',
    messagingSenderId: '167742209744',
    projectId: 'skykraft-e7fb7',
    storageBucket: 'skykraft-e7fb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPXH3iGabrDu7qDyJsOYUQ73Kr0ZOJgTs',
    appId: '1:167742209744:ios:cd5cef83bd99083669e8d5',
    messagingSenderId: '167742209744',
    projectId: 'skykraft-e7fb7',
    storageBucket: 'skykraft-e7fb7.appspot.com',
    iosBundleId: 'in.skykraft.SkyKraftUserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0xF39u8Tj7IbGd84qJUwVGXCC50IeQuo',
    appId: '1:167742209744:web:904f166cf0a60c8d69e8d5',
    messagingSenderId: '167742209744',
    projectId: 'skykraft-e7fb7',
    authDomain: 'skykraft-e7fb7.firebaseapp.com',
    storageBucket: 'skykraft-e7fb7.appspot.com',
    measurementId: 'G-9JXMKRY2DK',
  );

}